//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.06 at 09:56:52 PM MSK 
//


package Persistence.RecordType;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Persistence.RecordType package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Records_QNAME = new QName("", "records");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Persistence.RecordType
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RecordsType }
     * 
     */
    public RecordsType createRecordsType() {
        return new RecordsType();
    }

    /**
     * Create an instance of {@link UserRecordType }
     * 
     */
    public UserRecordType createUserRecordType() {
        return new UserRecordType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RecordsType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "records")
    public JAXBElement<RecordsType> createRecords(RecordsType value) {
        return new JAXBElement<RecordsType>(_Records_QNAME, RecordsType.class, null, value);
    }

}
